spring:
  jpa:
    hibernate:
      ddl-auto: update
  web:
    cors:
      allowed-origins: "http://localhost:4200","http://localhost:8080"
      allowed-methods: GET, POST, PUT, DELETE, PATCH
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
