package com.warhammer.ecom.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AllegianceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllegianceAllPropertiesEquals(Allegiance expected, Allegiance actual) {
        assertAllegianceAutoGeneratedPropertiesEquals(expected, actual);
        assertAllegianceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllegianceAllUpdatablePropertiesEquals(Allegiance expected, Allegiance actual) {
        assertAllegianceUpdatableFieldsEquals(expected, actual);
        assertAllegianceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllegianceAutoGeneratedPropertiesEquals(Allegiance expected, Allegiance actual) {
        assertThat(expected)
            .as("Verify Allegiance auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllegianceUpdatableFieldsEquals(Allegiance expected, Allegiance actual) {
        assertThat(expected)
            .as("Verify Allegiance relevant properties")
            .satisfies(e -> assertThat(e.getGroup()).as("check group").isEqualTo(actual.getGroup()))
            .satisfies(e -> assertThat(e.getFaction()).as("check faction").isEqualTo(actual.getFaction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllegianceUpdatableRelationshipsEquals(Allegiance expected, Allegiance actual) {
        // empty method
    }
}
