package com.warhammer.ecom.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommandLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommandLineAllPropertiesEquals(CommandLine expected, CommandLine actual) {
        assertCommandLineAutoGeneratedPropertiesEquals(expected, actual);
        assertCommandLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommandLineAllUpdatablePropertiesEquals(CommandLine expected, CommandLine actual) {
        assertCommandLineUpdatableFieldsEquals(expected, actual);
        assertCommandLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommandLineAutoGeneratedPropertiesEquals(CommandLine expected, CommandLine actual) {
        assertThat(expected)
            .as("Verify CommandLine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommandLineUpdatableFieldsEquals(CommandLine expected, CommandLine actual) {
        assertThat(expected)
            .as("Verify CommandLine relevant properties")
            .satisfies(e -> assertThat(e.getQuanity()).as("check quanity").isEqualTo(actual.getQuanity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommandLineUpdatableRelationshipsEquals(CommandLine expected, CommandLine actual) {
        assertThat(expected)
            .as("Verify CommandLine relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()))
            .satisfies(e -> assertThat(e.getCart()).as("check cart").isEqualTo(actual.getCart()));
    }
}
