name: Deploy the Spring Boot app in the cloud

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Copy jar to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          APP_JAR_NAME: ${{ secrets.APP_JAR_NAME }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no ./target/"$APP_JAR_NAME" $EC2_USER@$EC2_HOST:/home/ec2-user/back-end/

      - name: Restart Application on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          APP_JAR_NAME: ${{ secrets.APP_JAR_NAME }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          sudo pkill -f 'java -jar'
          nohup java -jar ./back-end/"$APP_JAR_NAME" > ./app.log 2>&1 &
          EOF
