name: Deploy JHipster App to EC2

# Exécute le pipeline à chaque push sur la branche 'main'
on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify the Node.js version you need

      # Step 3: Install dependencies and build front-end (if necessary)
      - name: Install npm depedencies
        run: npm install

      # Étape 2 : Configure Java et Maven pour compiler le projet JHipster
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw clean package -Pprod

      # Étape 3 : Préparation pour transférer le fichier JAR vers l'instance EC2
      - name: Prepare JAR file
        run: |
          echo "Jar file ready to be deployed"
          ls -l ./target/*.jar

      # Étape 4 : Copie du fichier .jar sur l'instance EC2 via SSH
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          APP_JAR_NAME: ${{ secrets.APP_JAR_NAME }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          echo "$EC2_KEY" > github-key.pem
          chmod 400 github-key.pem

          # Copie du fichier JAR sur l'instance EC2
          scp -i github-key.pem ./target/${APP_JAR_NAME} ec2-user@${EC2_HOST}:/home/ec2-user/

      # Étape 5 : Connexion SSH et redémarrage de l'application sur l'instance EC2
      - name: Restart application on EC2
        run: |
          ssh -i github-key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST}
          # Arrêt de l'application s'il y a un processus en cours
          PID=$(pgrep -f ${REMOTE_PATH}/${APP_JAR_NAME})
          if [ ! -z "$PID" ]; then
            echo "Stopping existing application with PID: $PID"
            kill -9 $PID
          fi

          # Redémarrage de l'application
          nohup java -jar ${REMOTE_PATH}/${APP_JAR_NAME} > app.log 2>&1 &
          echo "Application restarted successfully"
          EOF

      # Nettoyage de la clé privée après utilisation
      - name: Clean up
        run: rm ec2_key.pem
