name: Deploy JHipster App to EC2

# Exécute le pipeline à chaque push sur la branche 'main'
on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify the Node.js version you need

      # Step 3: Install dependencies and build front-end (if necessary)
      - name: Install npm depedencies
        run: npm install

      # Étape 2 : Configure Java et Maven pour compiler le projet JHipster
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw clean package -Pprod -DskipTests

      # Étape 3 : Préparation pour transférer le fichier JAR vers l'instance EC2
      - name: Prepare JAR file
        run: |
          echo "Jar file ready to be deployed"
          ls -l ./target/*.jar

      # Étape 4 : Copie du fichier .jar sur l'instance EC2 via SSH
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$PRIVATE_KEY" > github-key.pem
          chmod 400 github-key.pem
          # Copie du fichier JAR sur l'instance EC2
          # scp -i github-key.pem ./target/jhipsterlearn-0.0.1-SNAPSHOT.jar ec2-user@${HOST}:/home/ec2-user/

      # Étape 5 : Connexion SSH et redémarrage de l'application sur l'instance EC2
      - name: Restart application on EC2
        run: |
          ssh -i github-key.pem -o StrictHostKeyChecking=no ec2-user@${HOST}
          # test
          exit

      - name: try copy
        run: |
          scp -i github-key.pem ./target/jhipsterlearn-0.0.1-SNAPSHOT.jar ec2-user@13.60.71.207:/home/ec2-user/

      # Nettoyage de la clé privée après utilisation
      - name: Clean up
        run: rm ec2_key.pem
